export const SIZE = 11;

interface Palette {
    name: string;
    emoji: string;
    colors: string[];
    ideas: string[];
}

export const PALETTES: Palette[] = [
    {
        name: "Joyful",
        emoji: "😄",
        colors: [
            "#FFE7CC",
            "#FFD89E",
            "#FFC280",
            "#FFB266",
            "#FFA14D",
            "#FF9033",
            "#FF7F19",
            "#FF6E00",
        ],
        ideas: [
            "A sun with a smiling face.",
            "A balloon floating in the sky.",
            "A happy emoji.",
            "An ice cream cone.",
            "A dancing figure.",
            "A flower in full bloom.",
            "A jumping dolphin.",
            "A kite soaring high into the sky.",
            "A smiling heart shape.",
            "A star with rays of joy.",
        ],
    },
    {
        name: "Calm",
        emoji: "😌",
        colors: [
            "#CCE7CC",
            "#9ED89E",
            "#80C280",
            "#66B266",
            "#4DA14D",
            "#339033",
            "#198019",
            "#006E00",
        ],
        ideas: [
            "A peaceful tree silhouette.",
            "A serene lake or pond.",
            "A relaxing beach scene.",
            "A tranquil mountain.",
            "Some gentle waves.",
            "A candle flame.",
            "A meditating figure.",
            "A raindrop.",
            "A cloud drifting by.",
            "A zen garden arrangement.",
        ],
    },
    {
        name: "Sad",
        emoji: "😔",
        colors: [
            "#CCE7FF",
            "#9ED8FF",
            "#80C2FF",
            "#66B2FF",
            "#4DA1FF",
            "#3390FF",
            "#1980FF",
            "#006EFF",
        ],
        ideas: [
            "A raindrop falling.",
            "A drooping flower.",
            "A frowning face emoji.",
            "A cloud with rain.",
            "A dimmed sun.",
            "A lonely tree.",
            "A closed umbrella.",
            "A sad heart shape.",
            "A dripping paintbrush.",
        ],
    },
    {
        name: "Angry",
        emoji: "😡",
        colors: [
            "#FFD9D9",
            "#FFB2B2",
            "#FF8C8C",
            "#FF6666",
            "#FF4040",
            "#FF1A1A",
            "#E60000",
            "#C70000",
        ],
        ideas: [
            "A thunderbolt.",
            "A fire emoji.",
            "A sharp-edged lightning.",
            "A slashed line.",
            "An angry face.",
            "An explosion burst.",
            "A storm cloud.",
            "A range of ragged mountain.",
        ],
    },
    {
        name: "Grateful",
        emoji: "🙏",
        colors: [
            "#FFF2CC",
            "#FFE6B2",
            "#FFD999",
            "#FFCD7F",
            "#FFC266",
            "#FFB84D",
            "#FFAC33",
            "#FFA019",
        ],
        ideas: [
            "Hands in prayer.",
            "A grateful emoji.",
            "A heart and smiley face.",
            "The sun peeking through clouds.",
            "A blooming flower.",
            "A gift box with a bow.",
            "A butterfly in flight.",
            "A sparkling star.",
            "A smiling sunflower.",
        ],
    },
    {
        name: "Lonely",
        emoji: "😢",
        colors: [
            "#B3CCFF",
            "#99B7E6",
            "#809CCC",
            "#668DB3",
            "#4D789C",
            "#336480",
            "#1A3D66",
            "#004D4D",
        ],
        ideas: [
            "A single swing hanging.",
            "An empty park bench.",
            "A moonlit night.",
            "A lonely boat on a calm sea.",
            "A dim streetlamp.",
            "A distant lighthouse.",
            "A silent night sky.",
            "An isolated cabin.",
            "A long, winding road.",
            "A single star shining.",
        ],
    },
    {
        name: "Hopeful",
        emoji: "🕊️",
        colors: [
            "#ccffe0",
            "#b1e7c9",
            "#96d0b3",
            "#7cb99d",
            "#62a288",
            "#478c73",
            "#2b7760",
            "#00624d",
        ],
        ideas: [
            "A rising sun.",
            "A bird in flight.",
            "A shooting star.",
            "A seedling sprouting.",
            "A soaring kite.",
            "An open door.",
            "A beacon of light.",
            "A floating dandelion seeds.",
            "A crescent moon.",
        ],
    },
    {
        name: "Creative",
        emoji: "🎨",
        colors: [
            "#F2D9FF",
            "#D2B2FF",
            "#B380FF",
            "#9366FF",
            "#754DFF",
            "#5633FF",
            "#3A19FF",
            "#2100FF",
        ],
        ideas: [
            "A palette and paintbrush.",
            "An easel with canvas.",
            "A colorful swirl.",
            "Some abstract shapes.",
            "An artistic signature.",
            "An imaginative cloud.",
            "A paint splatter.",
        ],
    },
];
